# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_ratings', '0003_auto_20170217_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
            },
        ),
        migrations.AlterField(
            model_name='moviemark',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='Оцененный фильм'),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_ratings.MovieMark', verbose_name='Оценка'),
        ),
    ]
