# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings', '0004_auto_20170218_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='moviecomment',
            name='mark',
        ),
        migrations.DeleteModel(
            name='MovieComment',
        ),
    ]
