# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 00:41
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings', '0006_moviecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Содержание'),
        ),
    ]
