# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 01:17
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings', '0007_auto_20170220_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviemark',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterField(
            model_name='moviecomment',
            name='content',
            field=redactor.fields.RedactorField(blank=True, verbose_name='Содержание'),
        ),
    ]
