# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings', '0009_auto_20170221_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemark',
            name='value',
            field=models.DecimalField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], decimal_places=2, max_digits=4, verbose_name='Оценка'),
        ),
    ]
