# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_ratings', '0012_auto_20170221_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
    ]
