# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
