# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviemark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemark',
            name='author',
        ),
        migrations.RemoveField(
            model_name='moviemark',
            name='movie',
        ),
        migrations.DeleteModel(
            name='MovieMark',
        ),
    ]
