# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20170221_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actormovie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='actormovie',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='ActorMovie',
        ),
    ]
